leftnav:
- identifier: d9eb8c7e-b9ac-42db-83d1-5e36b8189f5d
  name: Section 1 Menu Title
  pageRef: /pages/section-1
  weight: 10
- identifier: 018d07b5-0f37-493f-8025-53a3ee837168
  name: Section 2 Menu Title
  pageRef: /pages/assignments
  weight: 20
- identifier: 7e1d1926-96b4-4f0c-b4b6-2f34ab7562f6
  name: Shortcode Demos
  pageRef: /pages/shortcode-demos
  weight: 30
- identifier: 7b3ae5c4-3b27-4806-b0c5-f012f16fa245
  name: Subscripts and Superscripts
  pageRef: /pages/subscripts-and-superscripts
  weight: 40
- identifier: a9916d12-f128-bdd2-a11b-02e75f786ba1
  name: Video Series Overview
  pageRef: /pages/video-series-overview
  weight: 50
- identifier: a7716d12-f128-bdd2-a11b-02e75f786ba1
  name: Multiple Videos Series Overview
  pageRef: /pages/multiple-videos-series-overview
  weight: 60
- identifier: 79392061-a205-4e93-83f2-276dbc9668e6
  name: Resource List
  pageRef: /lists/a-resource-list
  weight: 70
- identifier: 2f9c424e-c9ba-4d1e-b1f6-e89de1bf682a
  name: External Resources
  pageRef: /pages/external-resources-page
  weight: 80
- identifier: d1f35266-366e-45f1-bfc2-bcd46eb6c4a4
  name: Subsection 1a Menu Title
  pageRef: /pages/subsection-1a
  parent: d9eb8c7e-b9ac-42db-83d1-5e36b8189f5d
  weight: 10
- identifier: 874d2ec0-06db-40da-b376-4f6579590d20
  name: Subsection 1b Menu Title
  pageRef: /pages/subsection-1b
  parent: d9eb8c7e-b9ac-42db-83d1-5e36b8189f5d
  weight: 20
- identifier: 8ef7f3de-f238-4b3f-afb1-2d11a16f7247
  name: Google.com
  pageRef: /external-resources/googlecom
  parent: 2f9c424e-c9ba-4d1e-b1f6-e89de1bf682a
  weight: 10
